- src/plugins/coincap.js
The purpose of this task is to migrate the CoinCap plugin to the new API (/v2/assets instead of /front).
> Migrate CoinCap to new API

- CHANGELOG.md
- package.json
- src/index.js
- src/plugins/coincapLegacy.js
The purpose of this task is to add back the legacy API / exchange rates for Coincap so that the exchange rates that are missing from the newer API can be used within the GUI.
> Re-add old Coincap rates (legacy)

- src/swap/totle.js
Throw "No enabled exchanges support DAI to BAT" error for Totle quotes that use different sending and receiving wallets. Totle only allows transactions with a destination wallet that is the same as the source wallet.
> Implement same-wallet error throwing for Totle

- src/swap/totle.js
1. Change tokens URI to updated link.
1. Add user's destination address to the API request to support sending result of swap to a different address.
> Update Totle plugin.

- src/index.js
- src/swap/sideshift.js
This pull request adds the [SideShift.ai](https://sideshift.ai) exchange plugin to Edge Wallet.
`makeSideshiftPlugin` function is defined and added to the `index.js` file as described in the swap plugin integration [Wiki page](https://github.com/EdgeApp/edge-react-gui/wiki/Integration-of-a-swap-plugin). The plugin utilizes the [SideShift.ai REST API](https://sideshift.ai/api), first fetching `/rates` and `/permissions` to determine if the users location isn't restricted by SideShift.ai and the amount that the user is trying to exchange is between the `min` and `max` amount possible to shift. Then the `/quote` endpoint creates a fixed `quote` and based on that an `order` is created with the `/orders` endpoint. The data returned by SideShift.ai API is processed to an `EdgeSpendInfo` object …
> Add SideShift.ai exchange plugin

- src/swap/sideshift.js
This PR sends the refund address in the API request when an order is created through the SideShift.ai plugin. 
Currently users are required to manually enter their refund address on the SideShift.ai order page, which leads to many confused users and support tickets. With these changes, users will get refunded automatically if a refund is needed.
> Send refund address in API request in SideShift.ai plugin

- src/swap/totle.js
Fix for https://github.com/EdgeApp/edge-exchange-plugins/issues/130
> Sam/Totle Error Handling Fix

- src/swap-helpers.js
- src/swap/changenow.js
- src/swap/faast.js
- src/swap/shapeshift.js
- src/swap/sideshift.js
Many plugins use the pattern `new Date(Date.now() + expirationMs)`, which is obviously in the future. Other plugins use a date provided by the server, and they may need an adjustment if the phone's clock is wrong.
> Ensure that all quotes expire in the future

- src/swap/changelly.js
- src/swap/foxExchange.js
- src/swap/sideshift.js
- src/swap/switchain.js
This is a temporary measure to prevent users from trading FTM until exchange plugins can identify which mainnet chain they support. Among the active plugins, Changenow already has this in place and Godex is already upgraded to include mainnet in requests so no changes were necessary to their functionality.
> Disable FTM trading

- src/swap/sideshift.js
At the moment XRP transactions sent to SideShift.ai do not include the `destinationTag` returned by the SideShift API, therefore they are rejected by the XRP network.
This PR appends the `destinationTag` to the XRP transactions, so they will be processed successfully.
> Sideshift: include destinationTag in XRP tx

- src/swap-helpers.js
- src/swap/sideshift.js
Some partners, like Shapeshift and ChangeNow's v2 API, require lowercase codes.
---
- https://app.asana.com/0/0/1201573553283069
> Add lowerCase handling to getCodes

- src/swap/godex.js
Godex uses legacy addresses which can cause issues when a user attempts to send a max amount which is calculated assuming a segwit address.
---
- https://app.asana.com/0/0/1200755251532617
> Disable selling DGB to Godex

- src/swap/changelly.js
- src/swap/exolix.js
- src/swap/sideshift.js
These wallet methods used to search over all available plugins for a currency code match. The latest core update limits the currency code search to their respective plugin so we need to be more careful about which wallet we call these methods from.
---
- https://app.asana.com/0/0/1201910043204702
> Fix which engine to call denomination methods from

- src/swap/transfer.js
This was accidentally replaced by the pluginId check when BSC went live instead of added to
> Don't allow transfers if the currency code doesn't match

- src/swap/sideshift.js
Transcribes the AVAX currency code in the SideShift.ai plugin so users are able to exchange AVAX using SideShift.ai.
> Transcribe AVAX in SideShift plugin

- src/swap/changelly.js
Edge supports a different version of the token than Changelly
---
- https://app.asana.com/0/0/1202249984902683
> Block KNC on Changelly

- src/swap/defi/thorchain.js
Ensure native amounts are rounded to decimal. Otherwise getApprovalData would fail.
---
- https://app.asana.com/0/0/1202935772126432
> Fix reverse quotes with tokens as source

- src/swap/changehero.ts
The chainFrom and chainTo functionality isn't working so we need to limit EVM-like trades to ETH only. Issues found during testing are noted in comments.
---
- https://app.asana.com/0/0/1203218445109645
> ChangeHero: Revert invalid currency code change

- src/swap/swapuz.ts
The same quote request object is reused between all exchange plugins when multiple quotes are being fetched.
Ensure no mutations of this request happen.
> Remove mutation of quote request

- src/swap/changehero.ts
Enable 'to' quotes now that API is returning correct denoms
Re-enable token trades 
---
- https://app.asana.com/0/0/1203273323768305
> ChangeHero: Re-enable features

- src/swap/defi/thorchainDa.ts
---
- https://app.asana.com/0/0/1203598419533700
> Remove extra slash from thorswap URL

- src/swap/transfer.ts
Do not log quote object as this causes a cyclical reference error
---
- https://app.asana.com/0/0/1203614440093015
> Fix transfer plugin

- src/swap/godex.ts
The response for requested swaps below the minimums does not include chain info so it was getting caught in the unsupported error flow. I pinged Godex for clarity on how to tell which networks the min_amount applied to since we don't get to specify that before receiving the minimum error.
As far as I can tell, it is possible the returned min_amount might be for a different network than the user requests but it's probably better to show that than completely unsupported.
---
- https://app.asana.com/0/0/1203493677512989
> Godex: Flip minimum amount and network checks

- src/swap/letsexchange.ts
Generally, the network code is the mainnet currency code but that isn't always the case. These are the known exceptions.
---
- https://app.asana.com/0/0/1204121390970350
> LetsExchange: Audit and add special case mainnet codes

- src/swap/defi/lifi.ts
Estimate gas ourselves in the eth plugin as Lifi estimates too low of a gaslimit
none
none
none
---
- https://app.asana.com/0/0/1204220766101352
> Do not use LIFI gasLimit estimate for ethereum sends

- src/swap/defi/lifi.ts
RPC nodes are now unable to estimate gasLimit and cause fallback to 300000 gas which is insufficient for Lifi contracts.
none
none
none
---
- https://app.asana.com/0/0/1204422412177286
> Use Lifi gasLimit estimates for eth + 40%

- CHANGELOG.md
- src/swap/letsexchange.ts
- src/swap/swapuz.ts
- Fixed: Fix zkSync mainnet code transcription for LetsExchange.
- Fixed: Disable zkSync explicitly for Swapuz.
none
none
---
- https://app.asana.com/0/0/1204474155042560
> Explicitly disable zksync for swapuz

- src/swap/defi/lifi.ts
The LI.FI issue may be helped by this change, but no evidence to support that this completely fixes the problem.
- Fixed: Increased gas limit by 40% for all chains for LI.FI
none
none
---
- https://app.asana.com/0/0/1204953687205427
> Always use 40% gas limit increase for LI.FI

- src/swap/defi/lifi.ts
The mainnet value must be sent as it is calculated by the LI.FI API because it includes mainnet amount needed to pay for bridge fees within the smart contract.
- Fixed: LI.FI on-chain transactions no longer revert due to missing bridge fees
none
none
---
- https://app.asana.com/0/0/1204953687205427
> Use the `value` from the LI.FI quote response data directly

- CHANGELOG.md
- src/swap-helpers.ts
- src/swap/changehero.ts
- src/swap/changenow.ts
- src/swap/defi/lifi.ts
- src/swap/defi/thorchain.ts
- src/swap/defi/thorchainDa.ts
- src/swap/exolix.ts
- src/swap/godex.ts
- src/swap/letsexchange.ts
- src/swap/sideshift.ts
- src/swap/swapuz.ts
- src/swap/transfer.ts
We can't rely on their blockchain names to match ours so we need to whitelist them manually
---
- https://app.asana.com/0/0/1205417413219566
> Whitelist plugins for ChangeHero plugin

- CHANGELOG.md
- src/swap/defi/uni-v2-based/plugins/spookySwap.ts
- src/swap/defi/uni-v2-based/plugins/tombSwap.ts
- src/swap/defi/uni-v2-based/plugins/velodrome.ts
none
none
---
- https://app.asana.com/0/0/1205479436574240
> Fix spend target native amount

- CHANGELOG.md
- src/swap/defi/xrpDex.ts
none
none
---
- https://app.asana.com/0/0/1205862517383672
> Use max of 6 decimals for xrp dex

- CHANGELOG.md
- src/swap/defi/thorchain.ts
none
none
---
- https://app.asana.com/0/0/1205953809312301
> Fix thorchain min amount return error

- CHANGELOG.md
- src/swap/defi/thorchain.ts
- src/swap/defi/thorchainDa.ts
none
none
---
- https://app.asana.com/0/0/1205615584415945
> Add BSC support for Thorchain swaps

- package.json
- src/swap/changehero.ts
- src/swap/changenow.ts
- src/swap/defi/defiUtils.ts
- src/swap/defi/lifi.ts
- src/swap/defi/thorchain.ts
- src/swap/defi/thorchainDa.ts
- src/swap/defi/uni-v2-based/plugins/spookySwap.ts
- src/swap/defi/uni-v2-based/plugins/tombSwap.ts
- src/swap/defi/uni-v2-based/plugins/velodrome.ts
- src/swap/defi/xrpDex.ts
- src/swap/exolix.ts
- src/swap/godex.ts
- src/swap/letsexchange.ts
- src/swap/sideshift.ts
- src/swap/swapuz.ts
- src/swap/transfer.ts
- src/swap/types.ts
- src/util/swapHelpers.ts
- src/util/utils.ts
- test/fakeBchInfo.ts
- test/fakeBtcInfo.ts
- test/fakeCurrencyPlugin.ts
- test/testpartner.ts
- test/thorchain.test.ts
- yarn.lock
none
none
---
- https://app.asana.com/0/0/1206061725717248
> Paul/upgrade core2.0

- CHANGELOG.md
- src/swap/central/letsexchange.ts
- src/swap/defi/defiUtils.ts
- src/swap/defi/lifi.ts
- src/swap/defi/thorchain.ts
- src/swap/defi/thorchainDa.ts
- src/swap/defi/uni-v2-based/plugins/spookySwap.ts
- src/swap/defi/uni-v2-based/plugins/tombSwap.ts
- src/swap/defi/uni-v2-based/plugins/velodrome.ts
Latest edge-currency-accountbased removed use so we must use the new `memos` field or risk having memos dropped
none
none
---
- https://app.asana.com/0/0/1207003131677435
> Remove use of legacy memos

- CHANGELOG.md
- src/util/swapHelpers.ts
none
none
---
- https://app.asana.com/0/0/1206648078202433
> Return txid as orderId for DEX swaps when calling approve()

- CHANGELOG.md
- src/swap/defi/lifi.ts
https://github.com/EdgeApp/edge-currency-accountbased/pull/785
none
---
- https://app.asana.com/0/0/1207435891007623
> Lifi: Add Solana support

- src/index.ts
- src/swap/defi/rango.ts
- test/testconfig.ts
- test/testpartner.ts
none
New branch to address comments from https://github.com/EdgeApp/edge-exchange-plugins/pull/322
---
- https://app.asana.com/0/0/1207641048632567
> Add Rango Exchange plugin (take 2)

- CHANGELOG.md
- src/index.ts
- src/swap/defi/0x/0xGasless.ts
- src/swap/defi/0x/ZeroXApi.ts
- src/swap/defi/0x/constants.ts
- src/swap/defi/0x/types.ts
- src/swap/defi/0x/util.ts
- src/swap/defi/0x/zeroXApiTypes.ts
none
none
---
- https://app.asana.com/0/0/1207395251755815
> Implement 0xgasless swap

- CHANGELOG.md
- src/swap/defi/thorchain.ts
I don't have a clear understanding of the difference between streaming amounts and non-streaming amounts, but this fixes the cleaner error.
none
none
---
- https://app.asana.com/0/0/1207898557159096
> Leverage either amount fields from thorchain swap API

- CHANGELOG.md
- src/swap/defi/0x/0xGasless.ts
- src/util/due.ts
none
none
---
- https://app.asana.com/0/0/1207879659388405
> Implement max quotes for 0xGasless

- CHANGELOG.md
- package.json
- src/swap/defi/0x/0xGasless.ts
- src/swap/defi/0x/types.ts
- src/swap/defi/0x/zeroXApiTypes.ts
none
none
---
- https://app.asana.com/0/0/1208440926008971
> Add 0xGasless swap fee

- CHANGELOG.md
- src/swap/central/exolix.ts
- src/util/utils.ts
https://github.com/EdgeApp/edge-core-js/pull/626
https://github.com/EdgeApp/edge-currency-accountbased/pull/855
none
---
- https://app.asana.com/0/0/1208113757458927
> Add Zcash buys to Exolix

- CHANGELOG.md
- src/swap/central/changehero.ts
- src/swap/central/changenow.ts
- src/swap/central/exolix.ts
- src/swap/central/godex.ts
- src/swap/central/letsexchange.ts
- src/swap/central/sideshift.ts
- src/swap/central/swapuz.ts
- src/util/swapHelpers.ts
- test/partnerJson/changeheroMap.json
- test/partnerJson/changenowMap.json
- test/partnerJson/letsexchangeMap.json
- test/partnerJson/partnerJson.test.ts
- test/partnerJson/sideshiftMap.json
- test/testpartner.ts
none
none
---
- https://app.asana.com/0/0/1205921699940473
> Add dynamic whitelisting

- src/swap/defi/rango.ts
none
none
note : 
In my tests, selecting a non-native token from the Solana blockchain and entering a value below my maximum balance resulted in an "insufficient balance" error. However, using the "max" button worked without any issues.
---
- https://app.asana.com/0/0/1208425702564664
> Rango: Add Solana support

- CHANGELOG.md
- src/swap/defi/lifi.ts
- src/swap/defi/thorchain/swapkit.ts
none
none
---
- https://app.asana.com/0/0/1208710977099017
> Add BSC and RSK to DEXs

- CHANGELOG.md
- src/swap/defi/0x/0xGasless.ts
The dates for EdgeTransaction types are in unix seconds, not unix
milliseconds.
none
none
---
- https://app.asana.com/0/0/1208648365972985
> Fix incorrect date for 0xGasless EdgeTransaction

- CHANGELOG.md
- package.json
- src/index.ts
- src/swap/defi/defiUtils.ts
- src/swap/defi/lifi.ts
- src/swap/defi/rango.ts
- src/swap/defi/unizen.ts
- src/util/swapHelpers.ts
- test/unizen.test.ts
- yarn.lock
none
none
---
- https://app.asana.com/0/0/1208752773501973
> Add Unizen DEX

- CHANGELOG.md
- src/swap/defi/rango.ts
none
none
---
- https://app.asana.com/0/0/1209064047272954
> Fix Rango amount metadata

- CHANGELOG.md
- src/swap/defi/lifi.ts
The `fromNativeAmount` was previously referencing a value from the V1 quote that is `0x0` when swapping from a token.
Reference PR that last changed this: https://github.com/EdgeApp/edge-exchange-plugins/pull/281
Issue described from the prior change https://app.asana.com/1/9976422036640/project/1200382638405084/task/1204940534353339 was tested, a swap from POL -> USDC(Avalanche) works
none
none
---
- https://app.asana.com/0/0/1209776297342859
> Fix lifi tx amount

- CHANGELOG.md
- src/swap/central/changehero.ts
- src/swap/central/changenow.ts
- src/swap/central/exolix.ts
- src/swap/central/godex.ts
- src/swap/central/letsexchange.ts
- src/swap/central/sideshift.ts
- src/swap/central/swapuz.ts
- src/util/swapHelpers.ts
none
This PR adds eCash (XEC) cryptocurrency support to various swap providers in the edge-exchange-plugins repository, following the pattern of PR #375 which added PIVX support to centralized exchanges.
1. **Added 'ecash' to EdgeCurrencyPluginId type** in `src/util/swapHelpers.ts`
2. **Added XEC support to the following exchanges:**
- ChangeNow (with code 'xec')
- ChangeHero (with code 'xec')
- Exolix (with code 'XEC')
- Godex (with code 'XEC')
- LetsExchange (with code 'XEC')
- SideShift (with code 'ecash')
- SwapUz (with code 'XEC')
Through web searches, I confirmed that the following exchanges support eCash (XEC):
- **ChangeNow** - Confirmed XEC support (found exchange page at changenow.io/currencies/ecash)
- **Exolix** - Confirmed …
> Add eCash (XEC) support to centralized exchanges

- CHANGELOG.md
- src/swap/defi/thorchain/thorchainCommon.ts
The rate is bad and isn't close to etherscan low/normal/high and what we see from nodes. For example, when the baseFee was spiking around 11-13, the /quote response was recommending 3 or 4.
The plugin list changed because they either weren't supported or were nonsense values.
---
- https://app.asana.com/0/0/1210456727737137
> Ignore recommended fee rate for EVM currencies

- src/swap/types.ts
- src/util/swapHelpers.ts
none
- chain swap transactions by passing previous transactions to `makeSpend`
- allow `MakeTxParams` to include `pendingTxs`
- document every `makeSpend` invocation and whether it uses `pendingTxs`
---
- https://app.asana.com/0/0/1210515530676589
> Use pendingTxs in multi-tx swaps

- CHANGELOG.md
- src/swap/central/exolix.ts
Exolix doesn't support HyperEVM. It was mistakenly confused for HyperLiquid main network.
none
none
---
- https://app.asana.com/0/0/1210882648647106
> Remove HyperEVM from Exolix

- CHANGELOG.md
- package.json
- src/index.ts
- src/swap/defi/bridgeless.ts
- src/swap/types.ts
- src/util/swapHelpers.ts
- yarn.lock
https://github.com/EdgeApp/edge-currency-accountbased/pull/975
https://github.com/EdgeApp/edge-currency-plugins/pull/439
none
---
- https://app.asana.com/0/0/1210816418813844
> Add Bridgeless

- CHANGELOG.md
- src/swap/defi/lifi.ts
- src/util/swapHelpers.ts
- Add SUI to getParentTokenContractAddress() with native token address
- Add SUI to MAINNET_CODE_TRANSCRIPTION mapping
- Add SUI transaction request cleaner (asTransactionRequestSui)
- Implement SUI-specific transaction building logic
- Handle SUI transactions similar to Solana (no approval needed)
- Update CHANGELOG.md with feature addition
SUI is now supported for DEX swaps through the LI.FI plugin with chain ID 9270000000000000
none
none
---
- https://app.asana.com/0/0/1210756559961635
> feat(lifi): add SUI blockchain support
