EdgeApp/edge-exchange-plugins

src/herc.js, src/index.js
Same code as HERC's pull request but added export so that it is readable by the GUI. Also for simplicity.
=> Add HERC's exchange

src/index.js, src/plugins/nomics.js
The purpose of this task is to add Nomics's API to the list of available exchange rates.
Asana Task: https://app.asana.com/0/361770107085503/1118743622578989/f
=> Add Nomics exchange rates

src/swap-helpers.js, src/swap/changelly.js, src/swap/changenow.js, src/swap/faast.js, src/swap/shapeshift.js
Adds the isEstimate property passed to the quote helper to be surfaced to the app
=> add property for isEstimate to plugins

.gitignore, src/swap/changelly.js
lower case currency code causing error with incorrect amount on exact quote
=> fix currency case issue

src/index.js, src/react-native.js, webpack.config.js
This makes the build system more similar to edge-currency-bitcoin.
=> Fix startup crashes on old Android versions

src/swap/faast.js
Hey guys,
We've made some adjustments to the faast API and I've adjusted the plugin here to improve reliability. Some notes:
- I had given the wrong impression that the quotes were only estimates, as I was thought it was done a different way. With either the `deposit_amount` or `withdrawal_amount` provided, the price is guaranteed until the expiration (`price_locked_until`). So I've flipped that flag in the call to `makeSwapPluginQuote`.
- It will now use our /address endpoint to validate the addresses, and will use the `standardized` version of the address that we provide for swap creation. This is to help LTC and BCH swaps (eg. for LTC it converts the address from an '3...' to a 'M...' address.
- There's a limit check when the `quoteFor` is "from" as well as "to" now, by checking …
=> adjustments and fixes for faast plugin

src/index.js, src/swap/foxExchange.js
fox.exchange implementation as discussed
=> Fox swap plugin

src/index.js, src/swap/coinswitch.js
Supersedes: https://github.com/EdgeApp/edge-exchange-plugins/pull/18
coinswitch plugin integration
Change Coinswitch isEstimate to true
=> Add Coinswitch as Swap Partner

src/swap/changelly.js, src/swap/changenow.js
The purpose of this task is to allow our swap partners to be able to exchange currencies whose Edge currencyCodes are ambiguous (because they do not identify the parent chain, eg USDT).
=> Implement currencyCode transcription for inconsistent currency codes

README.md
Wow, this file was super out-of-date.
=> Update the out-of-date readme file

src/swap/faast.js
This fixes support for faast XRP swaps
=> Support faast uniqueIdentifier

src/index.js, src/rate/coinbase.js, src/rate/coincap.js, src/rate/compound.js, src/rate/constantRate.js, src/rate/currencyconverterapi.js, src/rate/herc.js, src/rate/nomics.js, src/rate/xagau.js, src/swap-helpers.js, src/swap/changelly.js, src/swap/changenow.js, src/swap/coinswitch.js, src/swap/faast.js, src/swap/foxExchange.js, src/swap/godex.js, src/swap/shapeshift.js, src/swap/totle.js
This implements the changes demanded by EdgeApp/edge-core-js#285
=> Upgrade to edge-core-js v0.17.0

package.json, src/swap/changenow.js, yarn.lock
This still needs testing, but I think the basic idea is here.
=> Add cleaners to the ChangeNow plugin

src/index.js, src/swap/totle.js, src/swap/transfer.js
Create a swap plugin that is a simple transfer to different address of the same chain.
=> 1:1 Transfer Swap Plugin

src/swap/changelly.js
New method doesn't need min/max checking since the Changelly response indicates if the trade is possible or not rather than returning acceptable amounts for a range pair. Error code is generic and the error message string would need to be parsed to determine which limit wasn't met
=> Update Changelly to getFixRateForAmount

src/rate/coingecko.js, src/rate/nomics.js
Also includes small fixes:
Coingecko
- fallback price support for ANTv1
- Save BTC price if requested fiat isn't available for since very few fiat codes are supported
Nomics
- Prevent querying if both codes are fiat or crypto, both of which aren't supported by endpoint
=> Add ANT support to coingecko

src/rate/coingecko.js, src/rate/constantRate.js, src/swap/switchain.js
Added tbtc to coingecko to ensure there's a rate
=> Update test bitcoin currency code across all plugins

src/swap/sideshift.js
=> Add order status URL

src/rate/coingecko.js, src/rate/constantRate.js
Move ANTV1 to constantRate plugin
=> Convert coingecko plugin from single to bulk query

src/swap/sideshift.js
Plugin should first determine if a requested pair can be serviced at all before checking location and amounts.
=> Move permission check after the rate check

src/swap/faast.js, src/swap/godex.js
And check Fox requests for mainnet currency code
=> Add mainnet currency codes to Godex requests

src/rate/bitmax.js
=> Update bitmax plugin URL

src/swap/sideshift.js
Related: https://github.com/EdgeApp/edge-currency-plugins/pull/187
=> Fix Core Type Imports

src/swap/sideshift.js
---
- https://app.asana.com/0/0/1201411731543809
=> Use the correct currencyCode in the metadata

src/index.js, src/swap/exolix.js
Integration of Exolix as an Exchange provider.
---
- https://app.asana.com/0/0/1201456542293999
=> add exolix plugin

src/swap-helpers.js, src/swap/changelly.js, src/swap/changenow.js, src/swap/exolix.js, src/swap/foxExchange.js, src/swap/godex.js, src/swap/sideshift.js, src/swap/switchain.js
For now, disable trading tokens on the Polygon (MATIC) network. Now that the main chain is enabled we are disabling trading of the MATIC ERC20 token. 
---
- https://app.asana.com/0/0/1201548855261612
=> Add MATIC filtering

src/rate/coingecko.js
---
- https://app.asana.com/0/0/1201622251646314
=> Add AVAX to coingecko

src/swap-helpers.js, src/swap/changenow.js
---
- https://app.asana.com/0/0/1201121207881015
=> Upgrade to ChangeNow v2 API

src/swap/changelly.js, src/swap/changenow.js, src/swap/exolix.js, src/swap/foxExchange.js, src/swap/godex.js, src/swap/sideshift.js, src/swap/switchain.js
---
- https://app.asana.com/0/0/1201622506798632
=> Update invalid codes

src/swap/godex.js
---
- https://app.asana.com/0/0/1201642026855978
=> Limit AVAX trading to the c-chain

src/rate/coingecko.js, src/rate/constantRate.js
Fix Coingecko's ID for BNT
---
- https://app.asana.com/0/0/1201730913460339
=> Add new currencies

src/rate/coingecko.js, src/rate/nomics.js
---
- https://app.asana.com/0/0/1201767257247822
=> Add BOO unique IDs

src/rate/coingecko.js, src/swap/changelly.js, src/swap/exolix.js, src/swap/foxExchange.js, src/swap/godex.js, src/swap/sideshift.js, src/swap/switchain.js
Also fill out list of Aave tokens
---
- https://app.asana.com/0/0/1201832373927424
=> Add new Celo tokens

src/swap/exolix.js
I reached out to Exolix regarding ZEC z-address support and will update the PR if they respond before the next publish
=> Update Exolix to use mainnet:token params

src/swap-helpers.js, src/swap/changelly.js, src/swap/changenow.js, src/swap/exolix.js, src/swap/foxExchange.js, src/swap/godex.js, src/swap/sideshift.js, src/swap/switchain.js
---
- https://app.asana.com/0/0/1201862740301684
=> Add Binance Smart Chain

src/rate/coingecko.js, src/rate/constantRate.js
---
- https://app.asana.com/0/0/1202043181203876
=> Add TSHARE, TOMB, and MAI exchange rates.

src/index.js, src/swap/letsexchange.js
LetsExchange - exchange plugin
=> LetsExchange - exchange plugin FINAL

src/swap/changelly.js
---
- https://app.asana.com/0/0/1202288034748122
=> Changelly: Re-enable estimated rate swaps

src/swap/letsexchange.js
=> LetsExchange plugin api

src/swap/changehero.js
---
- https://app.asana.com/0/0/1202687715819288
- https://app.asana.com/0/0/1202692200023371
=> Do not allow ChangeHero to swap tokens that are EVM chains

src/swap/exolix.js
---
- https://app.asana.com/0/0/1202834837562692
=> Disable reverse quoting for Exolix

src/swap/changehero.js, src/swap/changenow.js, src/swap/defi/uni-v2-based/plugins/spookySwap.js, src/swap/defi/uni-v2-based/plugins/tombSwap.js, src/swap/exolix.js, src/swap/foxExchange.js, src/swap/godex.js, src/swap/letsexchange.js
This ensures we have fresh quotes to prevent refunded swap requests.
---
- https://app.asana.com/0/0/1202872656296580
=> Change timeouts to 60s default

.gitignore, package.json, src/index.js, src/swap-helpers.js, src/swap/defi/abi/THORCHAIN_SWAP_ABI.js, src/swap/defi/thorchain.js, src/util/utils.js, test/thorchain.test.js, yarn.lock
---
- https://app.asana.com/0/0/1201425242712343
=> Add Thorchain support

src/swap-helpers.js
Call saveTx after token approval transaction
OTS approved by @peachbits
=> Fix nonce when sending Thorchain tx

src/swap/changehero.ts
1. update plugin for new API 
2. update code for Typescript 
---
- https://app.asana.com/0/0/1203041573069564
=> ChangeHero Plugin

src/swap/defi/thorchain.ts
---
- https://app.asana.com/0/0/1203116953073024
=> Enable AVAX Swaps on Thorchain

src/swap/defi/thorchain.ts
---
- https://app.asana.com/0/0/1203162131822848
=> Dont let thorchain swap same assets

src/swap-helpers.ts, src/swap/foxExchange.ts, src/swap/switchain.ts
---
- https://app.asana.com/0/0/1199941647509956
=> Disable swapping to Tezos with dummy addresses

src/index.ts, src/swap/swapuz.ts
---
- https://app.asana.com/0/0/1203186613849114
=> Add Swapuz

src/swap/defi/thorchain.ts
---
- https://app.asana.com/0/0/1203074693132557
=> Fix thorchain minimum quotes

src/swap/swapuz.ts
---
- https://app.asana.com/0/0/1203246026138868
=> Fix incorrect native amount returned in swapData

src/swap/swapuz.ts, src/util/biggystringplus.ts
---
- https://app.asana.com/0/0/1203256232564105
=> Implement Swapuz TO quotes for like-kind assets

src/swap-helpers.ts
---
- https://app.asana.com/0/0/1202131454449219
=> Add same asset rejection to checkInvalidCodes helper method

src/swap-helpers.ts, src/swap/changehero.ts, src/swap/changenow.ts, src/swap/foxExchange.ts, src/swap/godex.ts, src/swap/letsexchange.ts, src/swap/sideshift.ts, src/swap/swapuz.ts
Fix min/max error amounts
Enhance currency code transcription
Block REPv1 trading
---
- https://app.asana.com/0/0/1201215869677093
- https://app.asana.com/0/0/1203172809621876
=> Swap partner fixes

.eslintrc.json, src/declare-modules.d.ts, src/index.ts, src/rate/bitmax.ts, src/rate/coinbase.ts, src/rate/coincap.ts, src/rate/coingecko.ts, src/rate/coinmonitor.ts, src/rate/currencyconverterapi.ts, src/rate/edgeRates.ts, src/rate/nomics.ts, src/rate/wazirx.ts, src/react-native.ts, src/swap/changehero.ts, src/swap/changenow.ts, src/swap/defi/thorchain.ts, src/swap/defi/uni-v2-based/plugins/spookySwap.ts, src/swap/defi/uni-v2-based/plugins/tombSwap.ts, src/swap/exolix.ts, src/swap/foxExchange.ts, src/swap/godex.ts, src/swap/letsexchange.ts, src/swap/sideshift.ts, src/swap/swapuz.ts, src/swap/switchain.ts, src/swap/transfer.ts, src/util/utils.ts
---
- https://app.asana.com/0/0/1203287918505544
=> Lint cleanup

src/swap/sideshift.ts
This is a rebase of PR https://github.com/EdgeApp/edge-exchange-plugins/pull/194 redone in typescript. Tested and working.
---
- https://app.asana.com/0/0/1203359357629896
=> Update Sideshift API to V2

src/util/matchJson.ts, test/fakeBtcInfo.ts, test/fakeCurrencyPlugin.ts, test/fakeEthInfo.ts, test/testpartner.ts
---
- https://app.asana.com/0/0/1203359209045189
=> Add testing framework to run plugins in Node

src/swap/defi/thorchainDa.ts
---
- https://app.asana.com/0/0/1203487494850463
=> Update ThorSwap API for DEX aggregator

src/swap/defi/thorchain.ts, src/swap/defi/thorchainDa.ts
---
- https://app.asana.com/0/0/1203472287438093
=> Only approve exact amount needed for token txs

src/swap/letsexchange.ts
---
- https://app.asana.com/0/0/1203638213285544
=> Fix max amount logic in letsexchange

src/swap/godex.ts, src/swap/letsexchange.ts, src/swap/types.ts, test/createUserDump.ts, test/fakeArrrInfo.ts, test/fakeUserDump.json, test/testpartner.ts
---
- https://app.asana.com/0/0/1203646088292080
=> Fix letsexchange cleaner

src/swap-helpers.ts, src/swap/changehero.ts, src/swap/changenow.ts, src/swap/defi/thorchain.ts, src/swap/defi/thorchainDa.ts, src/swap/defi/uni-v2-based/plugins/spookySwap.ts, src/swap/defi/uni-v2-based/plugins/tombSwap.ts, src/swap/defi/uni-v2-based/uniV2Utils.ts, src/swap/exolix.ts, src/swap/godex.ts, src/swap/letsexchange.ts, src/swap/sideshift.ts, src/swap/swapuz.ts, src/swap/switchain.ts, src/swap/transfer.ts
---
- https://app.asana.com/0/0/1203632680642482
=> Send swapPluginType in EdgeSwapInfo and EdgeSwapQuote

src/swap/changehero.ts, src/swap/changenow.ts, src/swap/exolix.ts, src/swap/godex.ts, src/swap/letsexchange.ts, src/swap/swapuz.ts
---
- https://app.asana.com/0/0/1203589412095414
=> Dont use legacy addresses

src/swap/defi/thorchain.ts, src/swap/defi/thorchainDa.ts
---
- https://app.asana.com/0/0/1203879199448851
=> Fix thorchain

src/swap-helpers.ts, src/swap/defi/thorchain.ts, src/swap/exolix.ts, src/swap/godex.ts, src/swap/letsexchange.ts, src/swap/sideshift.ts, src/swap/swapuz.ts
---
- https://app.asana.com/0/0/1203970651584029
=> Add Optimism

package.json, src/index.ts, src/swap/changehero.ts, src/swap/changenow.ts, src/swap/defi/defiUtils.ts, src/swap/defi/lifi.ts, src/swap/defi/thorchain.ts, src/swap/defi/thorchainDa.ts, src/swap/defi/uni-v2-based/uniV2Utils.ts, src/swap/exolix.ts, src/swap/godex.ts, src/swap/letsexchange.ts, src/swap/sideshift.ts, src/swap/swapuz.ts, src/swap/types.ts, src/util/biggystringplus.ts, src/util/utils.ts, test/createUserDump.ts, test/fakePolygonInfo.ts, test/fakeUserDump.json, test/testpartner.ts, yarn.lock
---
- https://app.asana.com/0/0/1203860324834591
=> Implement Lifi DEX aggregator

src/swap/defi/lifi.ts
none
none
none
---
- https://app.asana.com/0/0/1204150558060451
=> Lifi: Allow gas price lower than 1 gwei

src/index.ts, src/swap/defi/abi/VELODROME_V1_ROUTER_ABI.ts, src/swap/defi/abi/WRAPPED_OPTIMISM_ETH_ABI.ts, src/swap/defi/defiUtils.ts, src/swap/defi/uni-v2-based/plugins/spookySwap.ts, src/swap/defi/uni-v2-based/plugins/tombSwap.ts, src/swap/defi/uni-v2-based/plugins/velodrome.ts, src/swap/defi/uni-v2-based/uniV2Utils.ts
---
- https://app.asana.com/0/0/1204241528085405
=> Add Velodrome

src/swap/defi/lifi.ts
---
- https://app.asana.com/0/0/1204513039671508
=> Prevent passing gasLimit as a float

src/swap/exolix.ts
---
- https://app.asana.com/0/0/1204464594667832
=> Api updated to v2

src/swap/defi/thorchain.ts
none
none
none
---
- https://app.asana.com/0/0/1204553834059679
=> Prevent tc swaps that would cause negative dest amounts

src/swap/swapuz.ts
none
none
none
---
- https://app.asana.com/0/0/1204547160186261
=> Fix swapuz refund address

src/swap/letsexchange.ts, src/swap/swapuz.ts
---
- https://app.asana.com/0/0/1204972466068247
=> Prevent MATH trades from Swapuz and LetsExchange

src/rate/coinbase.ts, src/rate/coincap.ts, src/rate/coingecko.ts, src/rate/compound.ts, src/rate/edgeRates.ts, src/swap/changenow.ts, src/swap/defi/lifi.ts, src/swap/defi/thorchain.ts, src/swap/defi/thorchainDa.ts, src/swap/sideshift.ts, src/swap/swapuz.ts
- changed: Use `EdgeIo.fetchCors` for all requests.
none
none
---
- https://app.asana.com/0/0/1205163660837607
=> Use `EdgeIo.fetchCors` for all requests

src/swap/defi/xrpDex.ts
fixed: Max swap with XRP DEX 
none
none
---
- https://app.asana.com/0/0/1205349062615728
=> Implement max swap for xrp dex

src/swap/defi/thorchain.ts
added: Thorchain streaming spreads
none
none
---
- https://app.asana.com/0/0/1205371018874225
=> Add TC streaming spreads

src/swap/defi/uni-v2-based/uniV2Utils.ts
By using the RPC's estimate, we can be more accurate based on network
conditions especially for layer-2 chains. We add a 25% over-estimate
to lower risk of transaction reverts.
- changed: Use RPC gas estimates for Uniswap plugin
none
none
=> Use the RPC's gas estimate for transaction gasLimit

src/swap/defi/thorchain.ts
fixed: Failed non-streaming quotes for ETH>BTC
none
none
---
- https://app.asana.com/0/0/1205412692015332
=> Fix TC failed quotes for ETH>BTC

src/swap/defi/uni-v2-based/uniV2Utils.ts
---
- https://app.asana.com/0/0/1205453382012360
=> Use backup gasLimit in case estimateGas fails

src/swap/defi/thorchain.ts
fixed: Fix denomination when using 'to' quotes in Thorchain
none
none
---
- https://app.asana.com/0/0/1205495163140331
=> Fix 'to' quotes in Thorchain

src/swap/defi/uni-v2-based/plugins/spookySwap.ts, src/swap/defi/uni-v2-based/plugins/tombSwap.ts, src/swap/defi/uni-v2-based/plugins/velodrome.ts
---
- https://app.asana.com/0/0/1205491734626091
=> Fix data field placement

CHANGELOG.md, src/swap/changehero.ts, src/swap/changenow.ts, src/swap/defi/defiUtils.ts, src/swap/defi/thorchain.ts, src/swap/defi/uni-v2-based/plugins/spookySwap.ts, src/swap/defi/uni-v2-based/plugins/tombSwap.ts, src/swap/defi/uni-v2-based/plugins/velodrome.ts, src/swap/defi/uni-v2-based/uniV2Contracts.ts, src/swap/godex.ts, src/swap/letsexchange.ts, src/swap/sideshift.ts, src/swap/swapuz.ts
---
- https://app.asana.com/0/0/1205544705952481
=> Remove EdgeMetaToken usage

src/swap/defi/defiUtils.ts
---
- https://app.asana.com/0/0/1205593655295190
=> If swap requires a wrap function then correctly use the wrapped address

src/swap/defi/uni-v2-based/plugins/spookySwap.ts, src/swap/defi/uni-v2-based/plugins/tombSwap.ts, src/swap/defi/uni-v2-based/plugins/velodrome.ts, src/swap/defi/uni-v2-based/uniV2Utils.ts
---
- https://app.asana.com/0/0/1205609849103194
=> Throw an unsupported error if 0 amount is expected from trade

CHANGELOG.md, src/swap/godex.ts
---
- https://app.asana.com/0/0/1205458575795049
=> Godex: Enable Zcash receiving

CHANGELOG.md, src/swap/defi/thorchain.ts
none
none
---
- https://app.asana.com/0/0/1205733442381833
=> Make Thorchain give estimate quotes

CHANGELOG.md, src/swap/defi/thorchain.ts
none
none
---
- https://app.asana.com/0/0/1205816775184358
=> Fix thorchain to report isEstimate=true

CHANGELOG.md, src/swap/defi/xrpDex.ts
none
none
---
- https://app.asana.com/0/0/1205862517383662
=> Check maxSpendable in xrpdex

src/swap/changehero.ts, src/swap/changenow.ts, src/swap/godex.ts, src/swap/letsexchange.ts, src/swap/sideshift.ts, src/swap/swapuz.ts
---
- https://app.asana.com/0/0/1205891187384589
=> Update Polygon USDC/USDC.e handling

CHANGELOG.md, src/index.ts, src/swap/central/changehero.ts, src/swap/central/changenow.ts, src/swap/central/exolix.ts, src/swap/central/godex.ts, src/swap/central/letsexchange.ts, src/swap/central/sideshift.ts, src/swap/central/swapuz.ts, src/swap/defi/xrpDex.ts, src/swap/xrpDexInfo.ts, src/util/makeSwapPlugin.ts
none
We don't want to refactor everything all at once, but it looks like XRP is the one causing the crashes on iOS 13.
---
- https://app.asana.com/0/0/1206470834673677
=> Split package

CHANGELOG.md, src/swap/central/changenow.ts, src/swap/central/exolix.ts, src/swap/central/godex.ts, src/swap/central/swapuz.ts
none
none
---
- https://app.asana.com/0/0/1206699056933038
=> Whitelisting followup fixes

CHANGELOG.md, src/index.ts, src/swap/defi/cosmosIbc.ts
none
none
---
- https://app.asana.com/0/0/1205856665924158
=> Add Cosmos IBC transfer plugin

CHANGELOG.md, package.json, src/swap/defi/cosmosIbc.ts, yarn.lock
Also remove currencyCode comparison since the makeSpend will determine if a valid IBC transfer
---
- https://app.asana.com/0/0/1206719654783686
=> Validate send/receive addresses are cosmos based

CHANGELOG.md, src/swap/defi/cosmosIbc.ts
---
- https://app.asana.com/0/0/1206730344859384
=> Re-add currencyCode comparison in Cosmos IBC transfer plugin

src/swap/central/changehero.ts, src/swap/central/changenow.ts, src/swap/central/exolix.ts, src/swap/central/godex.ts, src/swap/central/letsexchange.ts, src/swap/central/sideshift.ts, src/swap/central/swapuz.ts
---
- https://app.asana.com/0/0/1206683661257163
=> Add Cardano

CHANGELOG.md, src/swap/central/changehero.ts, src/swap/central/changenow.ts, src/swap/central/exolix.ts, src/swap/central/godex.ts, src/swap/central/letsexchange.ts, src/swap/central/sideshift.ts, src/swap/central/swapuz.ts, src/swap/defi/thorchainDa.ts
none
none
---
- https://app.asana.com/0/0/1206952714281174
=> Use proper `EdgeMemo` API

CHANGELOG.md, src/swap/central/changehero.ts, src/swap/central/changenow.ts, src/swap/central/exolix.ts, src/swap/central/godex.ts, src/swap/central/letsexchange.ts, src/swap/central/sideshift.ts, src/swap/central/swapuz.ts, src/util/utils.ts
---
- https://app.asana.com/0/0/1207119155083810
=> Add special memo types for Ripple and Stellar

CHANGELOG.md, src/swap/defi/abi/VELODROME_V2_ROUTER_ABI.ts, src/swap/defi/uni-v2-based/plugins/velodrome.ts
---
- https://app.asana.com/0/0/1205609247105048
=> Add Velodrome router v2

CHANGELOG.md, src/swap/central/exolix.ts
none
none
---
- https://app.asana.com/0/0/1207368195607803
=> Enable ARRR on Exolix

CHANGELOG.md, src/swap/defi/rango.ts
Do not send ETH when swap source is a token
none
none
---
- https://app.asana.com/0/0/1207815321473028
=> Fix rango swaps failing

CHANGELOG.md, src/swap/defi/rango.ts
Prevents failures due to not sending any additional ETH to pay for bridge txs
none
none
---
- https://app.asana.com/0/0/1207860717417810
=> Set rango avoidNativeFee flag

CHANGELOG.md, src/swap/central/exolix.ts, src/swap/types.ts, src/util/utils.ts
none
none
---
- https://app.asana.com/0/0/1207484518411801
=> Cap Exolix to 70k

CHANGELOG.md, src/swap/defi/lifi.ts
none
none
---
- https://app.asana.com/0/0/1208469975014594
=> Add unique parent token addresses

CHANGELOG.md, src/swap/defi/thorchain/common.ts
none
none
---
- https://app.asana.com/0/0/1208452819429190
=> Fix precision on toExchangeAmount

CHANGELOG.md, src/swap/defi/thorchain/common.ts, src/swap/defi/thorchain/mayaprotocol.ts, src/swap/defi/thorchain/thorchain.ts, src/swap/defi/thorchain/thorchainDa.ts
none
none
---
- https://app.asana.com/0/0/1208493839593328
=> Fix thornode url handling

CHANGELOG.md, src/swap/central/changehero.ts, src/swap/central/changenow.ts, src/swap/central/exolix.ts, src/swap/central/godex.ts, src/swap/central/letsexchange.ts, src/swap/central/sideshift.ts, src/swap/central/swapuz.ts
none
none
---
- https://app.asana.com/0/0/1208326136611423
=> Add TON unique IDs

src/swap/defi/thorchain/common.ts
none
none
---
- https://app.asana.com/0/0/1208678306130075
=> Remove partial flag from thorchain and maya protocol

src/swap/central/sideshift.ts
Based on https://github.com/EdgeApp/edge-exchange-plugins/pull/353
=> Add secret header to SideShift

CHANGELOG.md, src/swap/central/exolix.ts, src/swap/central/godex.ts
none
none
---
- https://app.asana.com/0/0/1208888448558653
=> Prevent Polygon USDC/USDC.e trading on CEX partners that don't support contract addresses

CHANGELOG.md, src/swap/defi/thorchain/swapkit.ts
none
none
---
- https://app.asana.com/0/0/1208029581358376
=> Upgrade Swapkit to v2

CHANGELOG.md, src/swap/central/exolix.ts
none
none
---
- https://app.asana.com/0/0/1209253939815908
=> Use S-address for Digibyte swaps

CHANGELOG.md, src/swap/defi/thorchain/common.ts, src/swap/defi/thorchain/thorchain.ts
none
none
---
- https://app.asana.com/0/0/1209199800706693
=> Add support for Base network to thorchain

CHANGELOG.md, src/swap/defi/0x/0xGasless.ts
- **Fix spelling of identifier**
- **Fix 0xGasless plugin orderId**
- **Add orderUri to 0xGassless EdgeTxAction**
none
none
---
- https://app.asana.com/0/0/1209173118665459
=> sam/0xGassless orderId orderUri

CHANGELOG.md, src/swap/defi/thorchain/swapkit.ts
none
none
---
- https://app.asana.com/0/0/1209349691352510
=> Make sure memo exists for utxo swaps

CHANGELOG.md, src/swap/defi/defiUtils.ts, src/swap/defi/thorchain/common.ts
none
none
---
- https://app.asana.com/0/0/1209458441262827
=> Use depositWithExpiry for every EVM swap

src/swap/central/changehero.ts
none
none
---
- https://app.asana.com/0/0/1209438596391561
=> Update Changehero codes

src/swap/defi/thorchain/swapkit.ts
none
none
---
- https://app.asana.com/0/0/1209440740285938
=> Fix memo handling

src/swap/defi/xrp/xrpDexHelpers.ts, src/swap/defi/xrp/xrpDexTypes.ts, src/swap/defi/xrpDex.ts
none
none
---
- https://app.asana.com/0/0/1209501623963057
=> XRPDEX - don't convert currency field

CHANGELOG.md, src/swap/defi/thorchain/thorchainCommon.ts
none
none
---
- https://app.asana.com/0/0/1209589713356190
=> Use recommended gas rate for thorchain/maya swaps

CHANGELOG.md, src/swap/defi/0x/0xGasless.ts, src/swap/defi/0x/ZeroXApi.ts, src/swap/defi/0x/zeroXApiTypes.ts
https://0x.org/docs/upgrading/upgrading_to_gasless_v2
none
none
---
- https://app.asana.com/0/0/1208400988810616
=> Upgrade to 0x gasless v2

CHANGELOG.md, src/swap/central/changehero.ts, src/swap/central/changenow.ts, src/swap/central/exolix.ts, src/swap/central/godex.ts, src/swap/central/letsexchange.ts, src/swap/central/sideshift.ts, src/swap/central/swapuz.ts, src/util/swapHelpers.ts
Added to ChangeNow, Exolix, Godex, and LetsExchange.
none
none
---
- https://app.asana.com/0/0/1209817093314822
=> Add PIVX to centralized exchanges

CHANGELOG.md, src/swap/defi/rango.ts
none
none
---
- https://app.asana.com/0/0/1209778565588716
=> `orderUri` for rango

CHANGELOG.md, src/swap/defi/thorchain/thorchain.ts, src/swap/defi/thorchain/thorchainCommon.ts
none
none
---
- https://app.asana.com/0/0/1210119145068308
=> Add XRP and TCY support

src/swap/defi/uni-v2-based/plugins/velodrome.ts
none
none
---
- https://app.asana.com/0/0/1209776167803742
=> Update Velodrome rpc

CHANGELOG.md, src/swap/central/changehero.ts, src/swap/central/changenow.ts, src/swap/central/exolix.ts, src/swap/central/godex.ts, src/swap/central/letsexchange.ts, src/swap/central/sideshift.ts, src/swap/central/swapuz.ts, src/swap/defi/rango.ts, src/swap/defi/thorchain/swapkit.ts, src/swap/defi/thorchain/thorchainCommon.ts, src/swap/defi/unizen.ts, test/unizen.test.ts
none
none
---
- https://app.asana.com/0/0/1210346829771661
=> Use high fee setting across the board

CHANGELOG.md, src/index.ts, src/swap/defi/abi/FANTOM_SONIC_UPGRADE.ts, src/swap/defi/fantomSonicUpgrade.ts
none
none
---
- https://app.asana.com/0/0/1209518986413121
=> Add Fantom to Sonic bridge plugin

src/swap/defi/0x/0xGasless.ts, src/swap/defi/0x/ZeroXApi.ts, src/swap/defi/0x/zeroXApiTypes.ts
none
none
---
- https://app.asana.com/0/0/1209918996092092
=> Update 0xGasless orderUri

CHANGELOG.md, src/swap/defi/fantomSonicUpgrade.ts
none
none
---
- https://app.asana.com/0/0/1210465074510184
=> Label Fantom/Sonic Upgrade as a DEX

CHANGELOG.md, src/swap/defi/thorchain/thorchainCommon.ts
The amounts returned by the API are not correct
none
none
---
- https://app.asana.com/0/0/1210678405892019
=> Report undefined minimums for Thorchain

CHANGELOG.md, src/swap/central/changenow.ts, src/swap/central/letsexchange.ts, src/swap/central/sideshift.ts, src/util/swapHelpers.ts
none
none
---
- https://app.asana.com/0/0/1210793091272146
=> Add Sonic support

CHANGELOG.md, src/swap/defi/bridgeless.ts
https://github.com/EdgeApp/edge-currency-accountbased/pull/978
https://github.com/EdgeApp/react-native-zano/pull/8
none
---
- https://app.asana.com/0/0/1211349016941708
=> Fix Bridgeless Zano deposits
